version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://root:secretpass@mongodb:27017/portfolio?authSource=admin
      - JWT_SECRET=supersecretkey123
      - ADMIN_USER=pinhann
      - ADMIN_PASS=password123
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secretpass
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
